dataset:
  name: "Prophesee"  # 7 classes
  prophesee:
    dataset_path: "/root/autodl-tmp/Prophesee"   # ./prophesee_dlut
    object_classes: ['pedestrian', 'two wheeler', 'car', 'truck', 'bus', 'traffic sign', 'traffic light']
    #  depth of resnet, [18, 34, 50, 101, 152]
    depth: 18
    height: 720
    width: 1280
    resize: 512
    voxel_size: [ 1, 1, 4 ]
    max_num_points: 5
    max_voxels: 100000
    num_bins: 5
    nr_input_channels: 8

dir:
  log: "log/"
model:
  # ["retinanet", "RED"]
  model_name: "dmanet"
optim:
  seq_len: 10
  epoch: 30
  batch_size: 4
  init_lr: 2e-5
  exponential_decay: 0.98
  warm: 1
  tbptt: [-1]
checkpoint:
  save_dir: "/root/autodl-tmp/checkpoint"  # ./DMANet
  resume_training: False
  resume_file: ""
  # Networks trained for classification can be reused as starting point for object detection networks on trained the same dataset
  use_pretrained: False
  pretrained_model: "/root/code/AAAI_Event_based_detection/log/20250715-192816/checkpoints/model_step_7.pth"
hardware:
  # num_cpu_workers: {-1: auto, 0: main thread, >0: ...}
  num_cpu_workers: 2
  gpu_device: 0  # [0 or "cpu"]
